<a href="https://colab.research.google.com/github/GreenOrange44/AIR/blob/main/HandsOn/HyperParametricTesting/HyperParametricTesting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

We explore hyper para metric testing. The first model we will perfom with linear kernel of SVM, in that there is no parameters to finetune. SO after that we perform the same experiment with kerenl of SVM.

Here we will perform HyperParametric testing with a grid approach, where the c and gamma value's grid will be formed and for each combination(the cartesian product of it) of them will be used to test the performance and the best parameter will be chosen

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"


# Assign column names to the dataset
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
irisdata = pd.read_csv(url, names=colnames)

irisdata

X = irisdata.drop('Class', axis=1)
y = irisdata['Class']



from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30)




In [ ]:
# First doing with a good kernel for this, the linear. But here there isn't any need for hyperparametric testing

from sklearn.svm import SVC
svclassifier = SVC(kernel='linear',C=1.0)
svclassifier.fit(X_train, y_train)


y_pred = svclassifier.predict(X_test)


from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))


[[13  0  0]
 [ 0 15  0]
 [ 0  0 17]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       1.00      1.00      1.00        15
 Iris-virginica       1.00      1.00      1.00        17

       accuracy                           1.00        45
      macro avg       1.00      1.00      1.00        45
   weighted avg       1.00      1.00      1.00        45



Now let's do hyperparametric testing

In [ ]:
# Second doing with a rbf kernel for this. But here we do perform the hyperparametric testing


from sklearn.model_selection import GridSearchCV


# defining parameter range
param_grid = {'C': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 5, 8, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 1000],
      'gamma': [1, 0.5, 0.1, 0.05, 0.01, 0.001, 0.0001, 0.00001],
      'kernel': ['rbf']}


grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)


# fitting the model for grid search
grid.fit(X_train, y_train)


# print best parameter after tuning
print(grid.best_params_)


# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)


grid_predictions = grid.predict(X_test)


# print classification report
print(confusion_matrix(y_test,grid_predictions))
print(classification_report(y_test, grid_predictions))




In [ ]:
# Now trying to find the best poly SVM kernel for our


from sklearn.model_selection import GridSearchCV


# defining parameter range
param_grid = {'C': [1,2,3,4,5,6,7,10,15,20,25,30,35,40,45,50],
      'degree': [1, 2,3,4,5],
      'kernel': ['poly']}


grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)


# fitting the model for grid search
grid.fit(X_train, y_train)


# print best parameter after tuning
print(grid.best_params_)


# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)


grid_predictions = grid.predict(X_test)


# print classification report
print(confusion_matrix(y_test,grid_predictions))
print(classification_report(y_test, grid_predictions))


